### ISSUE TITLE
gf xss no such pattern

### ISSUE THREAD

**Issue by sajjadmd** [JoyGhoshs/0install#2]
I'm facing the gf tool problem. When I execute the command according to you. I get error which says: "no such pattern".
I need help.
![image](https://user-images.githubusercontent.com/8243232/155061081-31dc87bc-5907-43ce-959c-5205b5481ccb.png)

**Comment by JoyGhoshs** [comment]
hey install gf patterns manually from https://github.com/1ndianl33t/Gf-Patterns
